### ISSUE TITLE
incompatible with facedetailer

### ISSUE THREAD

**Issue by jabbap** [mpiquero7164/ComfyUI-SaveImgPrompt#1]
something is wrong with this node, once it loads the shell output of other nodes like mtb loses color, facedetailer fails to load(1) and quitting comfy is no longer clean(2) -- the problem seems to be related to logging 

(1)

[ for some reason after adding the SaveImgPrompt node comfy thinks that the facedetailer requirements we already have need to be installed (?) ] 

!! Requirements need to be installed
!! Installing requirements...

[ but we already have them so it just says : ]

Requirement already satisfied: (NAME)/facedetailer/requirements.txt (line 1)) (8.0.157)

[ over & over, loading facedetailer than fails w/ these two exceptions: ]

Traceback (most recent call last):
  File "/home/toor/comfy/ComfyUI/custom_nodes/facedetailer/__init__.py", line 9, in <module>
    from .FaceDetailer import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS

( ... )

AttributeError: 'Logger' object has no attribute 'close'

( ... )

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/toor/comfy/ComfyUI/nodes.py", line 1647, in load_custom_node
    module_spec.loader.exec_module(module)
    ^^^^^^^^^^^^^^^^^

(...) 

AttributeError: 'Logger' object has no attribute 'close'

[ after which we're told that comfy can't import facedetailer ]

Cannot import /home/toor/comfy/ComfyUI/custom_nodes/facedetailer module for custom nodes: 'Logger' object has no attribute 'close'

(2)

^C
Stopped server
Exception ignored in atexit callback: <function shutdown at 0x7ff67df25ee0>
Traceback (most recent call last):
  File "/usr/lib/python3.11/logging/__init__.py", line 2193, in shutdown
    h.close()
  File "/home/toor/.local/share/virtualenvs/comfy-oNpgBBxC/lib/python3.11/site-packages/absl/logging/__init__.py", line 944, in close
    self.stream.close()
    ^^^^^^^^^^^^^^^^^
AttributeError: 'Logger' object has no attribute 'close'

PS: I've never reported an issue before so I might not have done this correctly but I think you'll get the point :-)

**Comment by mpiquero1111** [comment]
OKay I will take alook tonight. Thanks.
